baseURL = "https://plexsystems.github.io"
languageCode = "en-us"
title = "Plex Engineering"
theme = "hugo-theme-minos"
disqusShortname= "plexengineering"
googleAnalytics = "UA-170945889-1"

[params]
  customCss = ["css/custom.css"]
