name: blog

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop
      
jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: v0.71.1
          extended: false
          args: --cleanDestinationDir --minify --verbose

      - name: Deploy Site
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v1
        with:
            target_branch: master
            build_dir: public
            fqdn: engineering.plex.com
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
